### PR TITLE
Avoid 1.0.0-beta4 breaking changes

### PR DESCRIPTION
**Pull request by chentsulin**

### CODE REVIEW

**Comment by tomchentw** [comment]
Thanks!

**Comment by hungtuchen** [comment]
How does change to react-router 1.0.0-beta4 break any functionality?
Is there any known API change which will cause the break? because I haven't seen any doc for the new release

**Comment by chentsulin** [comment]
Um...so many breaking changes in `react-router 1.0.0-beta4`:
- `router` is not put in context any more (this.context.router), and put a `history` instead (this.context.history)

``` diff
-    router: PropTypes.object.isRequired,
+    history: PropTypes.object.isRequired,
```
- history has been moved to a independent module https://github.com/rackt/history
- now using `createHistory` function instead of history constructor

``` diff
-import {history} from "react-router/lib/BrowserHistory";
+import {createHistory} from "history";
```
- transition with history `pushState`, not router `transitionTo`:

``` diff
-    this.context.router.transitionTo("/search", {
+    this.context.history.pushState(null, "/search", {
       q: term,
     });
```
- if you want to use `transitionTo` directly, should create a location as parameter

``` js
import { createLocation, Actions } from "history";

//... same as .history.pushState(state, path)
const location = createLocation(path, state, Actions.PUSH, history.createKey());
history.transitionTo(location);
```
- `onEnter` interface, `redirectTo` instead of `transition`:

``` diff
-        onEnter(state, transition) {
+        onEnter(state, redirectTo) {
           // You may choose to render a 404 PageView here.
-          transition.to("/");
+          redirectTo("/");
         },
```
- `Router.run` has been removed, maybe use `history.match` instead (see [**tests**/serverRendering-test.js](https://github.com/rackt/react-router/blob/master/modules/__tests__/serverRendering-test.js))

And some else I not yet figure out..

**Comment by hungtuchen** [comment]
Wow, thanks @chentsulin 
I have heard of the history part would move to an independent module.
But I thought that will be at official 1.0 release, and the new API is more close to universal idea.
Thanks for sharing, :+1:

**Comment by chentsulin** [comment]
history module's doc maybe helpful on those changes:
http://rackt.github.io/history

and some reference on [useRoutes.js](https://github.com/rackt/react-router/blob/master/modules/useRoutes.js) (called createHistory decorator or history enhancer)

**Comment by loopmode** [comment]
Thanks for this info!

**Comment by timdorr** [comment]
> Router.run has been removed, maybe use history.match instead (see tests/serverRendering-test.js)

Nope, you can just use a `Router` component. See here: 

**server.js**

``` js
import createHistory from 'history/lib/createMemoryHistory';
import createLocation from 'history/lib/createLocation';
import Router from 'react-router';

import createRoutes from './routes';

const location = createLocation(req.originalUrl);
const history = createHistory({entries: [location]});
const routes = createRoutes();
const router = <Router history={history} children={routes} />;

res.render(template, {
  content: ReactDOM.renderToString(router)
});
```

**client.js**

``` js
import Router from 'react-router';
import createHistory from 'history/lib/createBrowserHistory';

import createRoutes from './routes';

const history = createHistory();
const routes = createRoutes(l);

ReactDOM.render(
  <Router history={history} children={routes} />,
  document.getElementById('scidx-container')
);
```

If you need transition hooks, you add those to the `history` object now.

**Comment by chentsulin** [comment]
https://github.com/rackt/react-router/issues/1806#issuecomment-138104481

So in beta5, will use `<RoutingContext />` instead of `<Router />` for server rendering.

See: https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md

Let's waiting for beta5.

**Pull request merged**
